// Generated by CoffeeScript 1.7.1
(function() {
  var random_in_interval;

  random_in_interval = function(a, b) {
    return a + Math.floor(Math.random() * (b - a));
  };

  window.timers = {
    random: function(init_delay, low_ms, high_ms) {
      return {
        init_delay: init_delay,
        next: function(w, t) {
          return random_in_interval(low_ms, high_ms);
        }
      };
    },
    bursts: function(init_delay, low_ms, high_ms, bursts, burst_ms) {
      return {
        n: 0,
        init_delay: init_delay,
        next: function(w, t) {
          this.n++;
          if (this.n % bursts === 0) {
            return random_in_interval(low_ms, high_ms);
          } else {
            return burst_ms;
          }
        }
      };
    }
  };

}).call(this);
